language: node_js
os:
  - linux
  - windows
node_js:
  - "4"
  - "5"
  - "6"
  - "stable"
sudo: false
before_script:
  - npm install
script:
  - npm run build
  - npm run test
cache:
  directories:
    - node_modules